//! Common optional fields accepted by every macro: `tags`, `since`, `note`.
//!
//! Each macro's `Parse` impl calls `CommonFields::take_field_if_known`
//! when it encounters an unknown identifier, so the common fields are
//! recognised wherever they appear in field order.

use serde::{Deserialize, Serialize};
use syn::{bracketed, parse::ParseStream, punctuated::Punctuated, Ident, LitStr, Token};

cast::concept! {
    name: "tags_field",
    summary: "Concepts/edges/rules carry a list `tags: [\"a\", \"b\"]`. \
              The list lets a concept live in more than one cross-cutting \
              group (e.g. `tags: [\"cast_web\", \"on_disk_protocol\"]`) \
              without forcing one tag to win. Downstream filters \
              (`where: { tag: ... }`, `where: { tag_not: ... }`, \
              `graph_for_tag`) match if any member of the list equals \
              the queried name. Empty list (`tags: []`) is legal — \
              represents an explicitly untagged annotation.",
    anchors: [
        crate::parser::common::CommonFields,
    ],
    tags: ["cast_grammar"],
}

#[derive(Debug, Clone, Default)]
pub struct CommonFields {
    pub tags: Vec<String>,
    pub since: Option<String>,
    pub note: Option<String>,
    /// Whether `tags` has been seen in this macro body. We can't just
    /// rely on `tags.is_empty()` because empty-list assignment is legal
    /// — the duplicate-field guard needs its own bit.
    tag_field_seen: bool,
}

impl CommonFields {
    /// If `name` is a recognised common field, parse its value and store.
    /// Returns `Ok(true)` if consumed, `Ok(false)` if `name` is not a
    /// common field, `Err` if the value was malformed or duplicated.
    pub fn take_field_if_known(
        &mut self,
        name: &Ident,
        input: ParseStream,
    ) -> syn::Result<bool> {
        let name_str = name.to_string();
        match name_str.as_str() {
            "tags" => {
                if self.tag_field_seen {
                    return Err(syn::Error::new(
                        name.span(),
                        "duplicate field: tags",
                    ));
                }
                input.parse::<Token![:]>()?;
                let content;
                bracketed!(content in input);
                let punct: Punctuated<LitStr, Token![,]> =
                    Punctuated::parse_terminated(&content)?;
                self.tags.extend(punct.into_iter().map(|l| l.value()));
                self.tag_field_seen = true;
                Ok(true)
            }
            "since" | "note" => {
                let slot = match name_str.as_str() {
                    "since" => &mut self.since,
                    "note" => &mut self.note,
                    _ => unreachable!(),
                };
                if slot.is_some() {
                    return Err(syn::Error::new(
                        name.span(),
                        format!("duplicate field: {name_str}"),
                    ));
                }
                input.parse::<Token![:]>()?;
                let lit: LitStr = input.parse()?;
                *slot = Some(lit.value());
                Ok(true)
            }
            _ => Ok(false),
        }
    }

    /// Convenience for downstream code that's interested in "is this
    /// concept tagged with X?" rather than the whole list.
    pub fn has_tag(&self, t: &str) -> bool {
        self.tags.iter().any(|s| s == t)
    }
}

/// Value of a `why:` field on a `continues_in!` / `io::continues_in!`
/// edge. Either prose the writer typed, or the bare ident `lazy` —
/// a deferred marker meaning "fill this in later (or generate it on
/// demand when a consumer asks)".
///
/// Wire format (serde): `Lazy` → `{"kind":"lazy"}`,
/// `Prose("...")` → `{"kind":"prose","text":"..."}`. Stable shape so
/// downstream tooling can filter by `kind == "lazy"` without parsing
/// the prose payload.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum WhyValue {
    /// Deferred: no prose yet. The writer marked the edge `why: lazy`
    /// because the structural connection was the load-bearing
    /// information; the prose justification can be generated by an
    /// LLM in a background pass or filled in on demand. Distinct from
    /// `None` (which means "no why field provided"): `Lazy` is an
    /// explicit instruction that an explanation is wanted but not yet
    /// written.
    Lazy,
    /// Prose typed by the writer.
    Prose { text: String },
}

cast::concept! {
    name: "lazy_why_marker",
    summary: "Sentinel ident `lazy` on a continues_in / io::continues_in \
              `why:` field. Means the structural edge is intentional \
              but the prose justification is deferred — fill in later, \
              or generate on demand.",
    anchors: [
        crate::parser::common::WhyValue,
    ],
    tags: ["cast_grammar"],
}

cast::continues_in! {
    target: cast_stdlib::type_properties::sum_type,
    concept: "lazy_why_marker",
    why: "Two-variant enum (Lazy, Prose) — the feature this block \
          dogfoods. Uses prose (not `why: lazy`) here only because the \
          running cast-watch was compiled before the new grammar \
          landed; on next force-restart this can switch to `why: lazy`.",
}
